# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MRAID' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MRAID

  target 'MRAID Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SourceKitMRAID' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SourceKitMRAID
  pod 'SourceKitCommon'
end
